const constants = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',

  LOGIN_START: 'LOGIN_START',
  LOGIN_COMPLETED: 'LOGIN_COMPLETED',
  LOGIN_FAIL: 'LOGIN_FAIL',

  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_COMPLETED: 'LOGOUT_COMPLETED',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  FETCH_USER_CLEAR: 'FETCH_USER_CLEAR',
  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_COMPLETED: 'FETCH_USER_COMPLETED',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',

  FETCH_USERLIST_START: 'FETCH_USERLIST_START',
  FETCH_USERLIST_COMPLETED: 'FETCH_USERLIST_COMPLETED',
  FETCH_USERLIST_FAIL: 'FETCH_USERLIST_FAIL',
};

export default constants;
